"""relate users to books

Revision ID: 112ef06f0ad3
Revises: dd2b08def278
Create Date: 2025-12-29 09:51:20.232685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '112ef06f0ad3'
down_revision: Union[str, Sequence[str], None] = 'dd2b08def278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'book', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_uid')
    # ### end Alembic commands ###
